name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Pack
      run: dotnet pack --configuration Release --no-restore
      
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Add Nuget GPR Source
      run: nuget source Add -Name "GitHub" -Source "https://nuget.pkg.github.com/VerdantSparks/index.json"
    
    - name: Setup Nuget API Key
      run: nuget setApiKey ${{ secrets.GITHUB_TOKEN }} -Source "GitHub"
      
    - name: Publish
      run: dotnet nuget push "bin/Release/verdantsparks.locationData.*.nupkg" --source "GitHub"

